import Head from "next/head";
import Navbar from "@/components/Navbar/Navbar";
import Editor from "@/components/Editor";
import { Box } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box className="h-screen bg-grey-50">
          <Navbar />
        </Box>
      </main>
    </>
  );
}
